#!/usr/bin/env bash
RED='\033[1;31m'
GREEN='\033[1;32m'
YLLW='\033[1;33m'
NC='\033[0m'
# Check if running as root user
if [ "$EUID" -ne 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nThis script needs to run as ${YLLW}root user${NC}, please use \"${GREEN}sudo ./uninstaller${NC}\" instead";
	exit 1;
fi



# Removing TVA-shield-mono in the list of aviable themes
echo -n "Updating plymouth themes alternatives   >>>   " ;
update-alternatives --remove default.plymouth /usr/share/plymouth/themes/TVA-shield-mono/TVA-shield-mono.plymouth &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nError occoured removing alternative in /usr/share/plymouth/themes/default.plymouth" ;
	exit 1;
fi
echo -e "[${GREEN}OK${NC}]" ;



# Setting a new default plymouth theme;
echo -e "Asking user to set a different theme    >>>   [${GREEN}OK${NC}]" ;
echo -e "\nDEFAULT OPTIONS ARE:" ;
echo -e "for Ubuntu based systems   ...   2  /usr/share/plymouth/themes/bgrt/bgrt.plymouth\n" ;
update-alternatives --config default.plymouth  ;
if [ $? -gt 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nError occoured setting alternative in /usr/share/plymouth/themes/default.plymouth";
	n=0 ;
	while [ $? -gt 0 -a $n -le 3 ]; do
		update-alternatives --config default.plymouth  ;
		n=$(( n+1 )) ;
	done
	exit 1;
fi



# Updating Initial RAM File System
echo -n "Updating Initial RAM File System   >>>   " ;
update-initramfs -u &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nError occoured executing \"update-initramfs -u\"";
	exit 1;
fi
echo -e "[${GREEN}OK${NC}]" ;



# Check if plymouth themes directory exist
if [ -d "/usr/share/plymouth/themes/TVA-shield-mono" ]; then
	echo -n "Removing /usr/share/plymouth/themes/TVA-shield   >>>   " ;
	rm -r /usr/share/plymouth/themes/TVA-shield-mono ;
	if [ $? -gt 0 ]; then
		echo -e "[${RED}ERROR${NC}]\nError occoured removing /usr/share/plymouth/themes/TVA-shield-mono" ;
		exit 1;
	fi
	echo -e "[${GREEN}OK${NC}]" ;
fi
