#!/usr/bin/env bash
RED='\033[1;31m'
GREEN='\033[1;32m'
YLLW='\033[1;33m'
NC='\033[0m'
# Comprobando permisos de administrador
if [ "$EUID" -ne 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nEste script necesita ejecutarse como ${YLLW}administrador${NC}, por favor utilice \"${GREEN}sudo ./desinstalador${NC}\" para ejecutar el archivo";
	exit 1;
fi



# Eliminando Sello-AVT de la lista de temas
echo -n "Actualizando lista de temas Plymouth                  >>>   " ;
update-alternatives --remove default.plymouth /usr/share/plymouth/themes/Sello-AVT/Sello-AVT.plymouth &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nHubo un fallo al remover el tema del archivo /usr/share/plymouth/themes/default.plymouth" ;
	exit 1;
fi
echo -e "[${GREEN}OK${NC}]" ;



# Asignando nuevo tema Plymouth predeterminado
echo -e "Consultando al usuario para asignar otro tema         >>>   [${GREEN}OK${NC}]" ;
echo -e "\nLAS OPCIONES SON:" ;
echo -e "Para su sistema   ...   /usr/share/plymouth/themes/bgrt/bgrt.plymouth\n" ;
update-alternatives --config default.plymouth  ;
if [ $? -gt 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nHubo un fallo al asignar otro tema en /usr/share/plymouth/themes/default.plymouth";
	n=0 ;
	while [ $? -gt 0 -a $n -le 3 ]; do
		update-alternatives --config default.plymouth  ;
		n=$(( n+1 )) ;
	done
	exit 1;
fi



# Actualizando sistema de archivos inicial de RAM
echo -n "Actualizando sistema de archivos inicial de RAM       >>>   " ;
update-initramfs -u &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "[${RED}ERROR${NC}]\nHubo un fallo al ejecutar \"update-initramfs -u\"";
	exit 1;
fi
echo -e "[${GREEN}OK${NC}]" ;



# Comprobando si aun existe la carpeta del tema
if [ -d "/usr/share/plymouth/themes/Sello-AVT" ]; then
	echo -n "Eliminando /usr/share/plymouth/themes/Sello-AVT       >>>   " ;
	rm -r /usr/share/plymouth/themes/Sello-AVT ;
	if [ $? -gt 0 ]; then
		echo -e "[${RED}ERROR${NC}]\nHubo un fallo al eliminar /usr/share/plymouth/themes/Sello-AVT" ;
		exit 1;
	fi
	echo -e "[${GREEN}OK${NC}]" ;
fi
